"""
DataVector models — data_vectors_<dim> bucket tables for the Data Agent's
training knowledge (DDL, documentation, verified question→SQL pairs, and
uploaded document chunks). EXACTLY the chunk_vectors pattern: one SQLAlchemy
model per catalog dimension, created by create_all — this REPLACES the
langchain_pg_* tables Vanna's stock store used, so every vector in the
platform lives in the same house pattern.

Rows carry their own text (content/question) — the store is self-contained:
    kind      'ddl' | 'documentation' | 'sql'
    question  only for kind='sql' (the NL question of a verified pair)
    tag       set for document-derived knowledge (the file name) — schema
              re-training wipes ONLY tag IS NULL rows, so uploaded documents
              survive a re-train and are removed by deleting the document.
"""
import logging
import uuid

from pgvector.sqlalchemy import HALFVEC, Vector
from sqlalchemy import Column, Computed, ForeignKey, Index, String, Text
from sqlalchemy.dialects.postgresql import TSVECTOR

from app.database import Base
from app.models.chunk_vector import (HNSW_HALFVEC_MAX, HNSW_VECTOR_MAX,
                                     catalog_dims)

logger = logging.getLogger(__name__)

_models: dict[int, type] = {}

# Language-aware full-text vector, GENERATED by PostgreSQL (never written by
# the app) — the keyword branch of hybrid retrieval. 'simple' keeps rare
# literal tokens (table/column names, KPI codes) intact, which is exactly
# what schema knowledge is made of.
_TSV_EXPR = ("to_tsvector('simple', coalesce(question,'') || ' ' || content)")


def data_vector_model(dim: int) -> type:
    """Mapped class for data_vectors_<dim>, built on first use."""
    dim = int(dim)
    if dim in _models:
        return _models[dim]

    table = f"data_vectors_{dim}"
    coltype = HALFVEC(dim) if dim > HNSW_VECTOR_MAX else Vector(dim)

    indexes = [
        Index(f"{table}_source_idx", "data_source_id", "kind"),
        Index(f"{table}_tsv_gin", "content_tsv", postgresql_using="gin"),
    ]
    if dim <= HNSW_HALFVEC_MAX:
        ops = "halfvec_cosine_ops" if dim > HNSW_VECTOR_MAX else "vector_cosine_ops"
        indexes.append(Index(
            f"{table}_hnsw", "embedding",
            postgresql_using="hnsw",
            postgresql_ops={"embedding": ops},
        ))
    else:
        logger.warning(f"[DATA-VEC] dim {dim} exceeds HNSW limits — unindexed")

    _models[dim] = type(
        f"DataVector{dim}",
        (Base,),
        {
            "__tablename__": table,
            "__table_args__": tuple(indexes),
            "id": Column(String, primary_key=True,
                         default=lambda: str(uuid.uuid4())),
            "data_source_id": Column(
                String, ForeignKey("data_sources.id", ondelete="CASCADE"),
                nullable=False),
            "kind": Column(String, nullable=False),      # ddl|business|sql
            "question": Column(Text, nullable=True),
            "content": Column(Text, nullable=False),
            "tag": Column(String, nullable=True),        # document file name
            "embedding": Column(coltype, nullable=False),
            # keyword branch — maintained by PostgreSQL, indexed with GIN
            "content_tsv": Column(TSVECTOR, Computed(_TSV_EXPR, persisted=True)),
        },
    )
    return _models[dim]


# Pre-build one model per catalog dimension so create_all sees every bucket.
for _dim in sorted(catalog_dims()):
    data_vector_model(_dim)
